-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PLANS TABLE
CREATE TABLE IF NOT EXISTS public.plans (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  price numeric NOT NULL,
  price_display text,
  period text DEFAULT '/mes',
  features text[] DEFAULT '{}',
  is_popular boolean DEFAULT false,
  description text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- RLS for Plans
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read access plans" ON public.plans;
CREATE POLICY "Public read access plans" ON public.plans FOR SELECT USING (active = true);
DROP POLICY IF EXISTS "Admin all access plans" ON public.plans;
CREATE POLICY "Admin all access plans" ON public.plans FOR ALL USING (auth.role() = 'authenticated');


-- 2. APP CONFIG TABLE
CREATE TABLE IF NOT EXISTS public.app_config (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  description text,
  updated_at timestamptz DEFAULT now()
);

-- RLS for App Config
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read access config" ON public.app_config;
CREATE POLICY "Public read access config" ON public.app_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin all access config" ON public.app_config;
CREATE POLICY "Admin all access config" ON public.app_config FOR ALL USING (auth.role() = 'authenticated');


-- 3. APPOINTMENTS TABLE
CREATE TABLE IF NOT EXISTS public.appointments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  patient_id uuid REFERENCES auth.users(id),
  date_time timestamptz NOT NULL,
  duration_minutes integer DEFAULT 60,
  status text DEFAULT 'scheduled',
  notes text,
  created_at timestamptz DEFAULT now()
);

-- RLS for Appointments
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own appointments" ON public.appointments;
CREATE POLICY "Users can view own appointments" ON public.appointments FOR SELECT USING (auth.uid() = patient_id);

DROP POLICY IF EXISTS "Users can create own appointments" ON public.appointments;
CREATE POLICY "Users can create own appointments" ON public.appointments FOR INSERT WITH CHECK (auth.uid() = patient_id);

DROP POLICY IF EXISTS "Admin manage all appointments" ON public.appointments;
CREATE POLICY "Admin manage all appointments" ON public.appointments FOR ALL USING (auth.role() = 'authenticated');


-- 4. ANTHROPOMETRICS TABLE
CREATE TABLE IF NOT EXISTS public.anthropometrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  
  -- General
  weight FLOAT,
  height FLOAT,
  age_at_record INTEGER,
  
  -- Folds
  fold_bicipital FLOAT,
  fold_tricipital FLOAT,
  fold_subscapular FLOAT,
  fold_suprailiac FLOAT,
  fold_calf FLOAT,
  fold_supraspinale FLOAT,
  
  -- Girths
  circ_waist FLOAT,
  circ_hip FLOAT,
  circ_calf FLOAT,
  circ_arm_relaxed FLOAT,
  circ_arm_contracted FLOAT,
  circ_wrist FLOAT,
  
  -- Diameters
  diam_humerus FLOAT,
  diam_femur FLOAT,
  diam_wrist FLOAT,
  
  -- Results
  mass_fat_kg FLOAT,
  mass_fat_pct FLOAT,
  mass_muscle_kg FLOAT,
  mass_muscle_pct FLOAT,
  mass_bone_kg FLOAT,
  mass_bone_pct FLOAT,
  mass_residual_kg FLOAT,
  mass_residual_pct FLOAT,
  
  somatotype_endomorph FLOAT,
  somatotype_mesomorph FLOAT,
  somatotype_ectomorph FLOAT,
  somatotype_x FLOAT,
  somatotype_y FLOAT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for Anthropometrics
ALTER TABLE public.anthropometrics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.anthropometrics;
CREATE POLICY "Enable read access for authenticated users" ON public.anthropometrics FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON public.anthropometrics;
CREATE POLICY "Enable insert access for authenticated users" ON public.anthropometrics FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update access for authenticated users" ON public.anthropometrics;
CREATE POLICY "Enable update access for authenticated users" ON public.anthropometrics FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete access for authenticated users" ON public.anthropometrics;
CREATE POLICY "Enable delete access for authenticated users" ON public.anthropometrics FOR DELETE USING (auth.role() = 'authenticated');


-- 5. SEED DATA (Only if not exists, logic handled by conflict or manual check mostly, but plain INSERTs might fail if violated. We use ON CONFLICT DO NOTHING for keys)

-- Initial Plans
INSERT INTO public.plans (name, price, price_display, period, features, is_popular, description)
VALUES 
('Básico', 24990, '$24.990', '/mes', ARRAY['Plan de alimentación personalizado','Evaluación antropométrica básica','Soporte por WhatsApp L-V','Rutina de ejercicios en casa'], false, 'Ideal para comenzar tu cambio'),
('Premium', 39990, '$39.990', '/mes', ARRAY['Todo lo del plan Básico','Análisis de composición corporal 3D','Seguimiento semanal detallado','Recetario exclusivo','Video llamada mensual 30min'], true, 'Nuestra opción más completa'),
('Trimestral', 99990, '$99.990', '/3 meses', ARRAY['Ahorro del 15% en total','Planificación a largo plazo','Suplementación deportiva guiada','Acceso a comunidad exclusiva'], false, 'Compromiso total con tu salud');
-- Note: Plans don't have unique keys so this might duplicate if run multiple times. User should truncate if needed.

-- Initial Config
INSERT INTO public.app_config (key, value, description)
VALUES 
('bank_details', '{
  "bank": "Banco Santander",
  "account": "12.345.678-9",
  "type": "Cuenta Corriente",
  "rut": "15.678.901-2",
  "name": "Verónica Amaya",
  "email": "contacto@nutriveronica.cl"
}'::jsonb, 'Datos de transferencia bancaria'),
('contact_info', '{
  "whatsapp": "56962265626",
  "email": "contacto@nutriveronica.cl"
}'::jsonb, 'Información de contacto general'),
('availability', '{
  "monday": ["09:00", "10:00", "11:00", "12:00", "15:00", "16:00", "17:00", "18:00"],
  "tuesday": ["09:00", "10:00", "11:00", "12:00", "15:00", "16:00", "17:00", "18:00"],
  "wednesday": ["09:00", "10:00", "11:00", "12:00", "15:00", "16:00", "17:00", "18:00"],
  "thursday": ["09:00", "10:00", "11:00", "12:00", "15:00", "16:00", "17:00", "18:00"],
  "friday": ["09:00", "10:00", "11:00", "12:00", "15:00", "16:00"],
  "saturday": [],
  "sunday": []
}'::jsonb, 'Configuración semanal de horarios disponibles')
ON CONFLICT (key) DO NOTHING;
