-- Create Anthropometrics Table
CREATE TABLE IF NOT EXISTS anthropometrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  
  -- Generales
  weight FLOAT,
  height FLOAT,
  age_at_record INTEGER,
  
  -- Pliegues (mm)
  fold_bicipital FLOAT,
  fold_tricipital FLOAT,
  fold_subscapular FLOAT,
  fold_suprailiac FLOAT,
  fold_calf FLOAT,
  fold_supraspinale FLOAT,
  
  -- Circunferencias (cm)
  circ_waist FLOAT,
  circ_hip FLOAT,
  circ_calf FLOAT,
  circ_arm_relaxed FLOAT,
  circ_arm_contracted FLOAT,
  circ_wrist FLOAT,
  
  -- Diámetros (cm)
  diam_humerus FLOAT,
  diam_femur FLOAT,
  diam_wrist FLOAT,
  
  -- Resultados Calculados
  mass_fat_kg FLOAT,
  mass_fat_pct FLOAT,
  mass_muscle_kg FLOAT,
  mass_muscle_pct FLOAT,
  mass_bone_kg FLOAT,
  mass_bone_pct FLOAT,
  mass_residual_kg FLOAT,
  mass_residual_pct FLOAT,
  
  somatotype_endomorph FLOAT,
  somatotype_mesomorph FLOAT,
  somatotype_ectomorph FLOAT,
  somatotype_x FLOAT,
  somatotype_y FLOAT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE anthropometrics ENABLE ROW LEVEL SECURITY;

-- Policy for reading (Nutritionist can read all, maybe limit later, strictly speaking patients should read their own but here we use a single nutritionist user for now or admin)
-- Assuming the user is the nutritionist managing data.
CREATE POLICY "Enable read access for authenticated users" ON anthropometrics
  FOR SELECT USING (auth.role() = 'authenticated');

-- Policy for insert
CREATE POLICY "Enable insert access for authenticated users" ON anthropometrics
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Policy for update
CREATE POLICY "Enable update access for authenticated users" ON anthropometrics
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Policy for delete
CREATE POLICY "Enable delete access for authenticated users" ON anthropometrics
  FOR DELETE USING (auth.role() = 'authenticated');
